import React from 'react';
import './Privacy.css';

import Container from '../Container';



class Privacy extends React.Component {

	highlightPrivacy(){
		document.getElementById("privacy").scrollIntoView({
			behavior: "smooth"
		});
	}

	render(){
		return(
			<Container title="Terms & Privacy" {...this.props}>
				<div className="Privacy">
					<div>
						<h2>Terms of Use</h2>


							These Terms of Use ("<strong>Terms</strong>") set out the terms that apply to your use of Kuīni Bot, made available by the Health Promotion Agency ("<strong>we</strong>" or "<strong>us</strong>").
							<p>These Terms are a legally binding contract. By using Kuīni Bot, you will be deemed to have agreed to be bound by them. Please read them carefully, and if you do not agree to any terms, you should stop using Kuīni Bot. </p>
							<p>We may change these Terms from time to time. We will send you a message in Kuīni Bot to tell you if we change these Terms.</p>
							<p>From time to time, we may make changes to or remove Kuīni Bot or content within it. Nothing in these Terms is a guarantee that Kuīni Bot will always be available, either in its current form or at all, or that we will support, maintain or continue to offer Kuīni Bot or any version of it.</p>
							<h3>Kuīni Bot does not provide health advice</h3>
							<p>Kuīni Bot has been developed for people who want to quit smoking, by providing general information to support them in that goal. Any information provided to you, or that you access through your use of Kuīni Bot, is not professional medical or health advice, diagnosis, or treatment, and is not a substitute for such advice, diagnosis, or treatment. </p>
							<p>The information that you provide when chatting with Kuīni Bot will not be monitored or verified by any health professionals. We do not warrant the accuracy, completeness, or usefulness of any information provided to you through your use of Kuīni Bot to help you quit smoking. </p>
							<p>We recommend that you contact your doctor or other health professional if you have any questions, or would like medical or health advice, about quitting smoking, or if you have any concerns about your smoking or your health more generally. </p>
							<h3>Your information and our privacy policy</h3> You can read about how we handle your information in our Privacy Policy [<a href="#privacy" onClick={this.highlightPrivacy}>here</a>].
							<h3>Licence</h3>
							<p>We grant you a non-transferable, non-exclusive licence to use Kuīni Bot, subject to these Terms.</p>
							<p>You must not:

							</p>
							<ol type='a'>
									<li>copy Kuīni Bot (or any content within it), except where permitted by law; </li>
									<li>rent, lease, sub-license, decompile, reverse-engineer, modify or create derivative works of Kuīni Bot or any of its content; </li>
									<li>rent, sell or transfer for commercial gain any content or output generated by use or operation of Kuīni Bot or its underlying systems; or </li>
									<li>interfere with or obscure any copyright notice we might include on Kuīni Bot.</li>
								</ol>
							<p>You must not:

							</p>
							<ol type='a'>
									<li>use Kuīni Bot in any unlawful manner, for any unlawful purpose, or in any manner inconsistent with these Terms, or act fraudulently or maliciously, for example, by hacking into or inserting malicious code, including viruses, or harmful data, into Kuīni Bot or any underlying system;</li>
									<li>infringe our intellectual property rights or those of any third party in relation to your use of Kuīni Bot; or</li>
									<li>transmit any material that is defamatory, offensive or otherwise objectionable.</li>
								</ol>
							<p>If you are accessing Kuīni Bot using Facebook Messenger, you must also comply with any applicable terms or conditions for use of Facebook Messenger. You are responsible for ensuring that you are aware of the applicable terms and conditions, and for your compliance with the applicable terms and conditions.</p>
							<h3>Intellectual property rights</h3>
							<p>You acknowledge that all intellectual property rights in Kuīni Bot or its contents anywhere in the world belong to us or our licensors. You have no rights in or to Kuīni Bot or any content within it, other than the right to use Kuīni Bot and its content in accordance with these Terms. All rights to the name, trade mark(s) and logo for Kuīni Bot remain our property. </p>
							<p>If you consider that any of the content in Kuīni Bot constitutes a breach of your intellectual property rights, you must immediately notify us of the alleged breach. If, after investigating your claim, we consider that the content breaches your intellectual property rights, we will remove the content in question as soon as is practicable.</p>
							<h3>Liability</h3>
							<p>Kuīni Bot and all content contained within it are provided on an "as is" and "as available" basis. Subject to any claim available under consumer protection laws, to the maximum extent permitted by law, (a) we (and all of our affiliates, agents, employees or contractors) expressly disclaim any and all warranties, express or implied, about Kuīni Bot or its content; and (b) we shall not be liable, whether in contract, tort (including negligence) or otherwise, for any losses (including any direct, indirect, consequential, special, exemplary or incidental damages, or for any lost profits, savings, revenue or data) arising out of or in connection with these Terms, Kuīni Bot and all content. </p>
							<p>Kuīni Bot may contain links to third party websites and content. We do not endorse such third party products, services or websites and have no liability in respect of your dealings with third parties.</p>
							<h3>Suspension and termination</h3> We may restrict or block your access to and use of Kuīni Bot at any time on a temporary or permanent basis if we reasonably believe that you may have breached any of these Terms.
							<h3>New Zealand law</h3> These Terms are governed by New Zealand law and the parties irrevocably submit to the exclusive jurisdiction of the New Zealand courts.
					</div>
					<div id="privacy">

							<h1>Privacy Policy</h1>
							<p>For you to get the most out of using Kuīni Bot, the Health Promotion Agency ("<strong>we</strong>" or "<strong>us</strong>") needs to collect some personal information about you. We will protect your personal information, and will only collect, use, store, and share it in accordance with the Privacy Act 1993.</p>
							This Privacy Policy sets out information about:
							<ul>
								<li>what information is collected by us through your use of Kuīni Bot; </li>
								<li>how your information will be used, stored, and shared;</li>
								<li>how you can access and change your personal information; and</li>
								<li>for how long we will hold your personal information. </li>
							</ul>
							In summary:
							<ul>
								<li>we collect personal information about you, including your gender, age and location and use it to personalise your Kuīni Bot experience, and can access some of your Facebook Messenger information;
								</li>
								<li>we share your information with our agents who help us provide Kuīni Bot to you;</li>
								<li>you can access your information through your Facebook Messenger account; and</li>
								<li>we will delete your information if you delete it from Facebook Messenger or 3 months after you stop using Kuīni Bot.</li>
							</ul>
							<p>This Privacy Policy forms part of the terms of use of Kuīni Bot. Your use of Kuīni Bot means that you accept and agree to the terms of this Privacy Policy and any changes to it.</p>
							We may change this Privacy Policy from time to time, including if we want to collect more information about you or use or share your information in another way. We will send you a message in Kuīni Bot to tell you if we change this Privacy Policy.
							<h3>What information do we collect?</h3>
							<h4>Personal information about you</h4> Kuīni Bot will ask for personal information about you through Kuīni Bot, including:
							<ul>
								<li>your gender;</li>
								<li>your age;</li>
								<li>your location;</li>
								<li>what you smoke (eg, rollies or cigarettes);</li>
								<li>your reason(s) for quitting; </li>
								<li>how you are feeling / how you are faring with quitting smoking. </li>
							</ul>
							<p>If you choose to answer those questions, we will collect that information. If you don’t want to answer those questions, you may be unable to use Kuīni Bot or Kuīni Bot may not be as effective for you because it will not have a complete picture about you and your reasons for quitting. </p>
							<p>We will also collect your messages with Kuīni Bot, including any personal information about you that you provide in your conversations with Kuīni Bot. </p>
							<h4>Aggregated, anonymous information about Kuīni Bot users</h4> We collect anonymous and aggregated information about you and all other Kuīni Bot users, including:
							<ul>
								<li>information users provide when chatting with Kuīni Bot, such as words and phrases that users use when messaging Kuīni Bot;</li>
								<li>when and how frequently users use Kuīni Bot;</li>
								<li>the total number of users of Kuīni Bot, and number of blocked users.</li>
							</ul>
							<h4>Facebook Messenger information</h4>
							<p>Because you are using Kuīni Bot through Facebook Messenger, we also have access to some information about your Facebook Messenger account, including your name, gender, Messenger ID, location and time zone, how you accessed Kuīni Bot, and your profile picture. </p>
							<p>We will not collect or have access to any other personal information that you provide to Facebook, and we will not have access to your Facebook profile. </p>
							<p>We will not post anything to your Facebook page or notify your friends that you are using Kuīni Bot. If you choose to post a GIF or video from your conversation with Kuīni Bot on your Facebook profile, your Facebook friends may see that it's from the Kuīni Bot page.</p>
							<p>Your use of Facebook Messenger, and the storage of personal information about you by Facebook, is subject to Facebook's privacy policy, which is available at <a href="https://www.facebook.com/policy.php">www.facebook.com/policy.php</a> or as otherwise notified by Facebook. Facebook will be able to see that you are using Kuīni Bot, and your messages with Kuīni Bot. </p>
							<h3>How do we use your information?</h3> The personal information that we collect from you via Kuīni Bot will be used to:
							<ul>
								<li>allow you to access, and chat with, Kuīni Bot; and</li>
								<li>personalise your experience of using Kuīni Bot. </li>
							</ul>
							We may use anonymous and aggregated information that we collect about users of Kuīni Bot so that we can analyse, evaluate, and improve Kuīni Bot, to improve our users' experience, and to help more people quit smoking.
							<h3>Will my information be shared with anyone else?</h3> We may share the personal information that we collect about you as follows:
							<ul>
								<li>we need to give some employees, contractors, agents and advisers access to the information you provide us to allow you to use Kuīni Bot. This includes our providers that host or maintain data centres where your information is processed or stored, service platforms, and other infrastructure and systems on our behalf; and</li>
								<li>as otherwise permitted by the Privacy Act 1993. </li>
							</ul>
							We may share anonymous and aggregated information about users of Kuīni Bot with public sector health agencies and other organisations and individuals that have an interest in understanding how people quit smoking.

							<h3>How is my information stored?</h3>
							<p>We take your privacy seriously, and will take all reasonable steps to ensure that your personal information is stored in a secure environment and protected from unauthorised access, use, modification, or disclosure.</p>
							<p>The personal information that you provide to us is held by us at The Health Promotion Agency, 101 The Terrace, Wellington, New Zealand.</p>
							<p>Your messages with Kuīni Bot will be stored in your Facebook Messenger account. You are responsible for ensuring that your Facebook Messenger account is kept safe and secure. You should also ensure that your device or computer is kept safe and secure, so that any personal information you provide when chatting with Kuīni Bot can only be accessed by you. </p>
							<h3>How do I access and change my information?  </h3> You can access information you provide when chatting with Kuīni Bot by going into your Facebook Messenger account. You can also access information, or request changes to your information, by contacting us at <a href="mailto:webmaster@hpa.org.nz">webmaster@hpa.org.nz</a>.
							<h3>For how long is my information held?</h3>
							<p>You may delete your conversations with Kuīni Bot at any time from your Facebook Messenger account. The personal information that we collect from you through your conversations with Kuīni Bot will be deleted if you delete your conversations. </p>
							<p>We will continue to hold your personal information as long as you continue to use Kuīni Bot, but will deleted it if you have not used Kuīni Bot for three months.</p>
							<p>If you choose to delete your conversations with Kuīni Bot, or you have not used Kuīni Bot for three months, you will need to answer the questions set out under What information do we collect if you want to start using Kuīni Bot again. </p>
						{/*
						<p><a href="#table">Back to Top</a>
						</p> */}
					</div>

				</div>

			</Container>
		)
	}
}

export default Privacy